### ISSUE TITLE
How can I mask my name

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens-registrar-dapp#100]
It seems like a majority of names are revealed (e.g. see Twitter bot). How can I make sure to not publicly share the name I'm bidding on? (I'm using registrar.ens.domains with metamask.)

**Comment by Arachnid** [comment]
Please see [this FAQ entry](http://docs.ens.domains/en/latest/faq.html#how-do-the-dapp-and-the-twitter-bot-know-what-names-people-are-auctioning).

Please consider asking these questions on Gitter, reddit, or the Ethereum Stack Exchange; issues aren't a great venue for tech support questions.
