### ISSUE TITLE
[Somewhat urgent] Cannot reveal "No accounts added to dapp"

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens-registrar-dapp#108]
This is my second auction with 40 hours to reveal. I am using Metamask with Chrome on http://registrar.ens.domains. I was able to reveal my first auction without problems. For this second auction when I click the reveal button I get the error "No accounts added to dapp". Nothing is logged to the JS console.

![screen shot 2017-05-09 at 17 36 10](https://cloud.githubusercontent.com/assets/731743/25861929/29328d0c-34de-11e7-943a-1244012429cb.png)

**Comment by Arachnid** [comment]
Try disabling then re-enabling your Metamask plugin, then signing in again.

**Comment by Stealth-Ether** [comment]
I am the same as above but it happens when I go to put my bid in.

Ether in Metamask account ready t pay but comes up with the red box above saying no accounts added to dapp

Did as you suggested but no joy.

**Comment by Stealth-Ether** [comment]
I have now tried it in Chrome via Metamask and now on Mist.
Same result on both browsers. Any suggestions?

**Comment by JustinDrake** [comment]
Disabling/reenabling worked for me 👍

**Comment by Stealth-Ether** [comment]
Did you just disable reenable through the settings tab or delete and reinstall?

**Comment by Stealth-Ether** [comment]
Yep. Worked for me but had to go through the disable/r-enable process three times but worked in the end.
