### ISSUE TITLE
What content hash for apps should I put in the editable field

### ISSUE THREAD

**Issue by Stealth-Ether** [ethereum/ens-registrar-dapp#137]
So I have secured my name (yay) and have linked it to my account which was fairly simple and straight forward.

The section under it for content hash for apps is defeating me a bit as I am still fairly new. What should go in this section?

Cheers in advance and I know you will be busy in the background due to ENS so can wait for an answer.
![ens grab](https://cloud.githubusercontent.com/assets/26900357/26064346/92e23a28-3988-11e7-9023-30efad503723.JPG)

**Comment by Arachnid** [comment]
If you have content you've deployed to swarm, you can put its hash there. If you don't, just leave it blank.

**Comment by Stealth-Ether** [comment]
Brilliant. Thanks. No need to do that yet then.

Cheers
