### ISSUE TITLE
ENS Dapp displays the wrong dates for some domains

### ISSUE THREAD

**Issue by JezSan** [ethereum/ens-registrar-dapp#147]
For instance for domain investor.eth - ENS dapp showed 3 days 23 hours til reveal phase, whereas myetherwallet shows 2 days 23 hours.   since more than 3 days is invalid, ENS Dapp is incorrectly displaying the dates.

<img width="935" alt="screen shot 2017-05-21 at 09 04 20" src="https://cloud.githubusercontent.com/assets/19607394/26284273/45946d1e-3e05-11e7-9091-38c54536d765.png">
<img width="1298" alt="screen shot 2017-05-21 at 09 05 02" src="https://cloud.githubusercontent.com/assets/19607394/26284274/459bf1ce-3e05-11e7-95ce-4198bd5db272.png">

**Comment by alexvandesande** [comment]
this is fixed now
