### ISSUE TITLE
End filters when navigating away from a name.

### ISSUE THREAD

**Issue by danfinlay** [ethereum/ens-registrar-dapp#153]
Currently it seems that the registrar Ðapp creates a number of filter subscriptions for each name viewed.

This is fairly expensive on bandwidth for remote providers, but is much worse because these filters seem to never be cancelled when navigating away, which should be part of the memory cleanup process, like deallocation.

At MetaMask we learned we weren't deallocating these as aggressively as we could, but the other half of the issue is Ðapps need to responsibly clean up.

**Comment by evertonfraga** [comment]
Hi @flyswatter, thanks for the heads up.

Currently I could only find two subscriptions throughout the code:  [`HashRegisteredEvent.watch`](https://github.com/ethereum/ens-registrar-dapp/blob/master/app/imports/lib/ethereum.js#L209) and [`AuctionStartedEvent.watch`](https://github.com/ethereum/ens-registrar-dapp/blob/master/app/imports/lib/ethereum.js#L166), which are set only once, and not for each name. Do you have any more detailed information about this? 

If you felt that the Dapp was sluggish, maybe it'll be better after this PR: https://github.com/ethereum/ens-registrar-dapp/pull/151

**Comment by evertonfraga** [comment]
Oh, think I found some code smells here. I am new to this codebase, sorry for that. I'll look into it. Thanks!

**Comment by evertonfraga** [comment]
This PR should help, until a proper refactor. https://github.com/ethereum/ens-registrar-dapp/pull/156

**Comment by danfinlay** [comment]
Thanks @evertonfraga for putting some time into it!

I based this issue off observations of network requests being made through MetaMask as this dapp was being used, but your code links seem to suggest my theory was wrong, that was maybe just a MetaMask issue that I'm working to solve.

Closing this for now since the issue described seems to have been a mis-diagnosis of a symptom.
