### ISSUE TITLE
Reveal not working

### ISSUE THREAD

**Issue by Gahete** [ethereum/ens-registrar-dapp#162]
Hi,

Some days ago I bid on an adress but now I can´t seem to reveal the bid because of the following problem (I´m using chrome btw):
After the transaction (https://etherscan.io/tx/0xf4813ee20c942a47efabb85266ef2e3249c2fe2fe929b9dc9c64d65e65d7ad20) I got no message to download any .json backup file, I´ve only got a screenshot with some text the website prompted me to save, so to speak the secret phrase and the secret SHA3. Also, the local storage in chrome doesnt seem to have saved the bid information. Is there any way to reveal my bid without having the .json file nor local information stored in the browser?
Regards,
Gahete

**Comment by Arachnid** [comment]
It looks like you bid using My Ether Wallet, not using registrar.ens.domains; this repository is for the latter. You should be able to reveal using the text you saved on MEW.
