### ISSUE TITLE
Not receiving a refund after reveal and finalising...

### ISSUE THREAD

**Issue by repran** [ethereum/ens-registrar-dapp#166]
Hi everyone.

As you can see I won the bid for limitededition.eth (https://etherscan.io/enslookup?q=limitededition.eth)

The internal transaction of the winning deed says that 4.99 ETH where sent to me as a refund (https://etherscan.io/address/0xe178c17cc8d15e7bd61d678a4117233a38f94047#internaltx)

But it does not show up on my address (https://etherscan.io/address/0xcbd482af76059e2a5e4a825c4cd5ced9f2dfe286)

How is this possible?

**Comment by Arachnid** [comment]
Check under 'internal transactions' on your address.

**Comment by NarryGan** [comment]
i have a similar situation where it says return amount from ENS is failed . how can we pull this into the wallet or re execute but this is incoming tx

https://etherscan.io/tx/0x0d6a828efa88b19c6a31f5ed10e05d31b1bd98a0bd27afadd35b8cd008ed16ef
