### ISSUE TITLE
Auction open, amount not transferred

### ISSUE THREAD

**Issue by aribo** [ethereum/ens-registrar-dapp#168]
I bid for a name using myetherwallet.eth. After I accepted the transactions, I checked it on etherscan. There were two transactions, as usual, one for 0 ether and the other for the amount I bid for (3.01 as hidden bid). The 0 ether tx went through, but the 3.01 tx was pending for 15 minutes and then it disappeared, so the ETH had not been transferred to the ENS.

Now, when I look up the name on etherscan or using ethers-ens it says the auction has been started by me. How is that possible is the bid amount is still in my account and there is no trace of the transaction for the transfer of funds (it's not pending either, it's just gone).

The account I used: 0x093fd69642c4173135b90b45059e744d8c1b63ed
The 0 eth transaction is this one: https://etherscan.io/tx/0x93150251774a79561b5159481409ba8c6f1f326436883b2981f7e613149b54f2

**Comment by Arachnid** [comment]
The 0 ether transaction is where you started the auction, but your bid transaction never went through. Go back to MEW, and you'll be able to place the bid again.

**Comment by aribo** [comment]
Thanks Nick. I thought that was the problem (I used very little gas, 2 Gwei is no longer secure I believe), so I bid for a smaller amount. Now that I know that was for certain the problem, can I increase my bid with another transaction?
