### ISSUE TITLE
registrar.ens.domains is down

### ISSUE THREAD

**Issue by chejazi** [ethereum/ens-registrar-dapp#171]
Getting a Github Pages 404 error.

"There isn't a GitHub Pages site here."

**Comment by manlabor** [comment]
I'm having the same issue using mist browser. Although, it started after an issue with win10 update.

**Comment by Arachnid** [comment]
This was a temporary issue due to a bad push.

**Comment by chejazi** [comment]
Is there a pre-commit hook to prevent this sort of thing? People relying on this site to manage active auctions could run into trouble down the line.
