### ISSUE TITLE
tx bad instruction

### ISSUE THREAD

**Issue by Oleski1** [ethereum/ens-registrar-dapp#181]
Hello my tx 0x6275e41d5bd372e03a0473f13a651f7ef9107eb2b180fe0b87557d015609f4d5 
was cancelled: 
 Warning! Error encountered during contract execution [Bad instruction] 
but ether was not refunded. Could you please to help me to get it back?

**Comment by Arachnid** [comment]
This is not the right place to ask for help with the Tezos crowdsale.
