### ISSUE TITLE
Metamask balance not showing my ETH

### ISSUE THREAD

**Issue by catchganu** [ethereum/ens-registrar-dapp#182]
Have transferred ETH from coinspot.com.au to Metamask using the address provided. Its more than 1 hr and it is yet to be received. 

This is my first time with Crypto currency, can some one advise or share their experience. 

it shows in my coinspot.com.au as success with the public address of my Metamask. How long does it generally take.

**Comment by Arachnid** [comment]
You need to take this up with coinspot or metamask.
