### ISSUE TITLE
buggy text entry for content hash

### ISSUE THREAD

**Issue by RMBLRX** [ethereum/ens-registrar-dapp#185]
I've got kind of a strange issue with the text entry field for content hashes on a domain I own:  When attempting to paste a copied IPFS hash into the field, it will only paste part of the address, selectively deleting portions of that address.  What I discovered upon further investigation is that  I could type a bunch of *S*s or *X*s and likely any number of other letters, but when I type *D*, it deletes all of those particular characters which precede the *D*.  That behavior seems to be what's affecting my pasting of the hash, as well as letters defaulting to lower-case (IPFS hashing is case-sensitive, I believe).

**Comment by Arachnid** [comment]
IPFS hashes aren't currently supported - only swarm hashes.

**Comment by RMBLRX** [comment]
Maybe I missed something, but I saw no indication anywhere that it wasn't supported, particularly since it says *IPFS/SWARM* right there in the UI.
