### ISSUE TITLE
ENS Bid revealed but the bid masked amount not returned to wallet . 

### ISSUE THREAD

**Issue by NarryGan** [ethereum/ens-registrar-dapp#203]
Revealed the bid after the window closed . should loose the bid amount but has to get back the bid masked amount .  I dont know for what reason is the transaction in fail state for the return amount .

https://etherscan.io/tx/0x0d6a828efa88b19c6a31f5ed10e05d31b1bd98a0bd27afadd35b8cd008ed16ef

**Comment by bitsnaps** [comment]
The gas limit is 200000 as i can see, are you sure that was enough? was this in the main net?

**Comment by NarryGan** [comment]
This is resolved
