### ISSUE TITLE
Throttle lookup so you can type smoothly

### ISSUE THREAD

**Issue by ferni** [ethereum/ens-registrar-dapp#26]
Right now you need to type the name slowly in order for it to register it properly, since it performs a lookup on every key press, resulting in the app stuttering.

**Comment by Arachnid** [comment]
More so, it needs to handle keypresses that occur during the lookup correctly - by adding them to the text and discarding the response when it comes.

**Comment by ferni** [comment]
Solved by https://github.com/ethereum/ens-registrar-dapp/pull/27
