### ISSUE TITLE
Time to bid issue in dapp!!!

### ISSUE THREAD

**Issue by rfikki** [ethereum/ens-registrar-dapp#71]
It is about 4:30 am CDT and I looked up a name, the name says it is available at 6:17 am CDT however the registrar dapp states less than an hour for bidding.

**Comment by Arachnid** [comment]
This is caused here: https://github.com/ethereum/ens-registrar-dapp/blob/3bff5b175663f5677198d87b52e7d66e856477f9/app/imports/templates/components/nameStatus.js#L288 - the test should be `>= 1`, not `> 1`.

**Comment by alexvandesande** [comment]
fix upcoming
