### ISSUE TITLE
Total number of auction days error! seven should be five...

### ISSUE THREAD

**Issue by rfikki** [ethereum/ens-registrar-dapp#75]
Names in Ethereum are used to send ether, to access apps and other future uses. Names are not "bought" from anyone, ownership is guaranteed by willingness to lock ether for at least a year on the domain. While the ether is locked, the owner retains the rights to the domain, including the right to add extradata, create subdomains, lease, loan, sell it or do anything with another smart contract. The full process takes **seven days** and the amount of ether to be locked will be decided by auction. If nobody tries to claim your name in the first week, then you'll be refunded all the funds other than the minimum amount of 0.01 ether, required.

**Comment by alexvandesande** [comment]
thanks I'm addressing on the next release soon
