### ISSUE TITLE
Dummy hashes not working undefined: Using Parity v.1.6.6 fully synced mainnet -- Try to click bid, this is the result.

### ISSUE THREAD

**Issue by veonindustries** [ethereum/ens-registrar-dapp#76]
Browser: Firefox (latest ubuntu 16.04 version)
Note: output is as a result of clicking bid multiple times repeatedly to generate the below results.
> Using the Parity browser

Dummy hashes not working undefined  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:9622
secret 374258850523440418172451916172763203002212757764813136649773012936694849604422852335804028289633  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:8879
Dummy hashes not working undefined  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:9622
secret 375138541177941902021996409415271472684690944314708638881669655300372695762334365226342867237434  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:8879
Dummy hashes not working undefined  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:9622
secret 1881015034412100330129108007462092567667207505025926845563691069393907394687135640161197521486868826  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:8879
Dummy hashes not working undefined  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:9622
secret 5568980561777689267298979266210205368201890890070235203740021538652481571531616065135521089724112  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:8879
Dummy hashes not working undefined  76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207:9622

**Comment by Arachnid** [comment]
This should be fixed now; please reopen if it's still not working for you.
