### ISSUE TITLE
no action after submitting a bid

### ISSUE THREAD

**Issue by voikol** [ethereum/ens-registrar-dapp#77]
I have participated in the auction for "exrnnrxe".

When I click "bid", then it seems to be processing, i.e. the button turns into "bidding". However, after a couple of second it turns back to "bid".

I have not done anything, but I have Metamask open. 

I am on a Mac version 10.10 and have used Chrome.

**Comment by Arachnid** [comment]
Can you please open the developer console in chrome (Command+Shift+I) and copy any error messages and logs you see and paste them into this bug?

**Comment by voikol** [comment]
MetaMask - injected web3
/i18n/de.json Failed to load resource: the server responded with a status of 404 (Not Found)
SourceSansPro-Semibold.otf Failed to load resource: the server responded with a status of 404 (Not Found)
SourceSansPro-ExtraLight.otf Failed to load resource: the server responded with a status of 404 (Not Found)
SourceSansPro-Bold.otf Failed to load resource: the server responded with a status of 404 (Not Found)
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 checkNetwork 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
SourceSansPro-Regular.otf Failed to load resource: the server responded with a status of 404 (Not Found)
/sockjs/info?cb=eyy5f74azc Failed to load resource: the server responded with a status of 404 (Not Found)
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 done initialiting null 0x6090a6e47849629b7245dfa1ca21d94cd15878ef
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 update Reveal Names:  
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 network?! main
SourceSansPro-Light.otf Failed to load resource: the server responded with a status of 404 (Not Found)
/preimages.js:1146803 Names loaded
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 1146799 known names loaded. Now checking for events since block 3647922
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 launchRatio 0.0016781568287245969
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 name: exrnnrxe
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:3 Exception from Tracker afterFlush function:
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:3 ReferenceError: BigNumber is not defined
    at t (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207)
    at o (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207)
    at h.View.<anonymous> (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207)
    at 76e77ac50d95382f4462038064ccd3eaf1692ca6.js:106
    at Function.e._withTemplateInstanceFunc (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:107)
    at 76e77ac50d95382f4462038064ccd3eaf1692ca6.js:106
    at Object.h._withCurrentView (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:106)
    at n (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:106)
    at o.Computation._compute (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:55)
    at new o.Computation (76e77ac50d95382f4462038064ccd3eaf1692ca6.js:55)
SourceSansPro-ExtraLightIt.otf Failed to load resource: the server responded with a status of 404 (Not Found)
Simple-Line-Icons.woff Failed to load resource: the server responded with a status of 404 (Not Found)
Simple-Line-Icons.ttf Failed to load resource: the server responded with a status of 404 (Not Found)
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 upsert exrnnrxe 0
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! roselandfurniture
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! untrochaic
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! vvoprose
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! screencast
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! vocicultural
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! elafoon
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! gametea
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! journeyworker
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! freedomhacker
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! mustafaercel
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! exrnnrxe
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! network1sports
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! iflashgame
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! payunity
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! groupseres
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! goldenlion
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! zhifubao
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 
 Watched name auction started! exxtrafamous
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 secret 1491305393208349681533606912746492127646873890823641292963375000129027367163242847354062957192882
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 Dummy hashes not working undefined
376e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 update Reveal Names:

**Comment by voikol** [comment]
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:207 secret 2104033161190557321425524491038213634901481404364393298027625317457027031501223552348097233743449
76e77ac50d95382f4462038064ccd3eaf1692ca6.js:209 update Reveal Names:

**Comment by voikol** [comment]
contentscript.js:2454 Error: PortDuplexStream - disconnected
    at PortDuplexStream._write (contentscript.js:207)
    at doWrite (contentscript.js:5016)
    at writeOrBuffer (contentscript.js:5005)
    at PortDuplexStream.Writable.write (contentscript.js:4943)
    at PostMessageStream.ondata (contentscript.js:4088)
    at PostMessageStream.EventEmitter.emit (contentscript.js:2454)
    at readableAddChunk (contentscript.js:3759)
    at PostMessageStream.Readable.push (contentscript.js:3718)
    at PostMessageStream._onMessage (contentscript.js:3185)

**Comment by Arachnid** [comment]
This should be fixed now; please reopen if it's still not working for you.
